In [6]:
#Python_Adv_Day4(Numpy_Day4)

import numpy as np
a=np.array([10,10,10])
b=np.array([5,5,5])

print('a+b=', a+b)
print('a-b=', a-b)
print('a*b=', a*b)
print('a/b=', a/b)
print('a%b=', a%b)

a+b= [15 15 15]
a-b= [5 5 5]
a*b= [50 50 50]
a/b= [2. 2. 2.]
a%b= [0 0 0]

In [7]:
a**2 
# It will do square of

array([100, 100, 100])

In [8]:
# Dot function (or) method

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print ('A:\n', A)
print ('B:\n', B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]

In [9]:
A*B # Element wise multiplication happen

array([[2, 0],
       [0, 4]])

In [10]:
A.dot(B) # Matrix multiplication

array([[5, 4],
       [3, 4]])

In [20]:
# Modifying an existing array rather than creating a new one.

a = np.array ([10,10,10])
b = np.array ([5,5,5])
a +=3
print(a)
b +=a
print(b)

[13 13 13]
[18 18 18]

In [25]:
# unary operations.
ages = np.array([12,15,18,20])
print('ages.sum =', ages.sum())
print('ages.min =', ages.min())
print('ages.max =', ages.max())

ages.sum = 65
ages.min = 12
ages.max = 20

In [27]:
numbers = np.arange(12).reshape(4,3)
numbers

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
numbers.sum()

66

In [30]:
# Aris - 0 --> Coloumn
# Aris - 1 --> Rows

numbers.sum(axis = 0)

array([18, 22, 26])

In [31]:
numbers.sum(axis = 1)

array([ 3, 12, 21, 30])

In [38]:
# Universal Functions : Trignometry, Arthamatic, Complex and Statistical Functions are called as Universal functions,
# Trignometric Functions:

angles = np.array([0,30,45,60,90])
# Angles need to be converted to radians by multiplying by pi/180
angles_radians = angles*np.pi/180
print (angles_radians)
print('SINE of angles in the array:')
print(np.sin(angles_radians))

print('\nTAN of angles in the array:')
print(np.tan(angles_radians))

print('\nCOS of angles in the array:')
print(np.cos(angles_radians))

[0.         0.52359878 0.78539816 1.04719755 1.57079633]
SINE of angles in the array:
[0.         0.5        0.70710678 0.8660254  1.        ]

TAN of angles in the array:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]

COS of angles in the array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

In [39]:
# Statistical Functions:
test_scores = np.array([32.32, 56.98, 21.52, 44.32, 55.63])
print('\nMean Test Scores of the students:')
print(np.mean(test_scores))

print('\nMedian Test Scores of the students:')
print(np.median(test_scores))

Mean Test Scores of the students:
42.153999999999996

Median Test Scores of the students:
44.32

In [48]:
salaries = np.genfromtxt('/home/andhavarapu/SW-DUMP/python_advance/numpy_data_sets/salary.csv',delimiter= ",")
salaries

array([ 60000.,  58000.,  56967.,  54000.,  70000.,  39000.,  36000.,
        26000.,  43000.,  75000.,  41411.,  36000.,  26000.,  40000.,
        40000.,  62000.,  30000.,  22680.,  27600.,  44000.,  32400.,
        56000., 261546.,  40000.,  77000.,  30819.,  42000., 500000.,
        77570.,  60000.,  42000.,  65000.,  60000., 120000.,  54000.,
        46860.,  81000.,  75000.,  75000.,  35000.,  43000.,  40000.,
        73000.,  14134.,  75000., 210000.,  90000.,  38400., 105227.,
        84000.,  48000.,  55000.,  98000.,  50000.,  22000.,  70000.,
        36000.,  36000.,  42000., 115000.,  72000.,  50000.,  49000.,
        30000.,  48000.,  25000.,  42000.,  57400.,  70000.,  53000.,
        31000.,  46000.,  50000.,  45000.,  50000.,  71796.,  47000.,
       130773., 103529.,  57000.,  45000.,  70000.,  40000.,  75000.,
        57000.,  22000.,  30514., 119875.,  60000.,  32000.,  46860.,
       132000., 100000.,  22000., 141671.,  87500.,  90000.,  65000.,
        30514.,  27440.,  30000.,  42000., 109100.,  25000.,  43200.,
        98080.,  53000.,  87689.,  25008., 550000.,  54000.,  56697.,
        43700.,  48000.,  22000.,  60000.,  49000., 180000.,  92000.,
        63000.,  40000.,  21000.,  36000., 220000.,  30000.,  66000.,
        36000.,  80000.,  30000.,  40000.,  32400.,  30000.,  38000.,
        23000.,  39500.,  50000.,  40000.,  45000.,  40000.,  65460.,
        50000.,  19500.,  54550.,  36000.,  28000.,  26500.,  65000.,
        40000.,  48000.,  30000.,  25500., 109294.,  30400.,  52000.,
        48000.,  50000.,  70000.,  35000.,  57758.,  27000.,  25500.,
        75000.,  75000.,  44000.,  47000.,  27000.,  18000.,  28366.,
        43638.,  50000.,  40000.,  38000.,  62662.,  64000.,  36600.,
        46000.,  25000.,  90000.,  60000.,  21800.,  31000.,  44000.,
        51000.,  60000.,  44000.,  70000.,  30000.,  45000.,  28000.,
        30000.,  42792.,  44500.,  54022.,  63000.,  80000.,  51500.,
        53000.,  55000.,  55000.,  45000.,  50000.,  30000.,  50600.,
        38142.,  47400.,  30000.,  49000.,  45000.,  40630.,  26000.,
        46500.,  46860.,  70000.,  21000.,  48000.,  32500.,  53000.,
        60000.,  30000.,  39000.,  90000., 135380.,  37000.,  13800.,
        22000.,  45000.,  34741.,  48000.,  50000.,  38000.,  44000.,
        31200.,  32000.,  65000.,  70000.,  49000., 103529.,  64000.,
        53000.,  52000.,  34000.,  70000., 120000., 185000.,  70000.,
        30000., 850000.,  48000.,  21000.,  53900.,  50000.,  44000.,
        55000.,  45000.,  28000.,  31200.,  61500.,  60000.,  42000.,
        32693.,  51250.,  20000.,  39000.,  32000.,  27000.,  42000.,
        35680.,  22300.,  40000.,  46800.,  63000., 181339.,  47500.,
        75665.,  50000.,  17000.,  36000.,  54000.,  58000.,  32693.,
        57000.,  54275.,  11400., 100000.,  46000.,  21400.,  53000.,
        15801.,  65000.,  62662.,  90000.,  43431.,  70835.,  75000.,
        34873.,  52000., 111600., 102000.,  48400.,  41956.,  60000.,
        65000.,  55000., 625000.,  28000., 100000.,  78000.,  32000.,
        42000.,  22910.,  36000.,  75000.,  60000.,  42000.,  33000.,
        53000.,  64000.,  37000.,  47500.,  48000.,  46913.,  63000.,
        59656.,  29000.,  43000.,  40000.,  55000.,  38142.,  48000.,
        52000.,  22000.,  40000.,  55000.,  69000.,  80750.,  84703.,
        40000., 110464.,  48500.,  54550.,  42000.,  50000.,  48000.,
       102000.,  56732.,  16800.,  55000.,  38000.,  63000.,  20000.,
        62000.,  50000.,  24000.,  60000.,  30000.,  50000.,  32000.,
        12450.,  44000.,  45000.,  50566.,  50000.,  70151.,  48000.,
        36000.,  60000.,  47000.,  22500.,  42000.,  56400.,  65000.,
        43000.,  48000.,  54000.,  33629.,  48000.,  42000.,  50000.,
       140000.,  17000.,  35000.,  75000.,  15400.,  23700.,  65000.,
       120000.,  37052.,  40000.,  51000., 820000.,  49095.,  41000.,
        16000.,  45000.,  37000.,  50500.,  80000.,  42000.,  38000.,
        20000.,  40000.,  22100., 250000.,  40800.,  33000.,  24400.,
        58000.,  47000., 130000.,  52854.,  30000.,  24800.,  28800.,
        85000.,  14000.,  44400.,  35774.,  39200.,  35000.,  60000.,
        29000.,  34000.,  55000.,  45000.,  26000.,  50000.,  49040.,
        36000.,  54000.,  65000.,  50000.,  71925., 136375.,  90000.,
        30000.,  36000., 141000.,  90000.,  30600.,  65000.,  36000.,
        66000.,  72000.,  65000.,  21795.,  48604.,  55000.,  18000.,
        50000.,  28236., 142800.,  43800.,  50000.,  68000., 116626.,
        65000.,  36000.,  45000.,  52309.,  56000.,  48000.,  20000.,
        22128.,  31000.,  48000.,  57758.,  58000.,  53000.,  28000.,
        26400.,  28000.,  60000.,  32000.,  60000.,  35000.,  97000.,
        67382.,  50000.,  45000.,  38049.,  26500.,  44000.,  54000.,
        43200.,  90000.,  40000.,  85000.,  41956.,  75000.,  40000.,
        57000.,  60000.,  48000.,  52000.,  24000.,  47300.,  76600.,
        50000.,  45000.,  41000.,  50000.,  26000.,  60000., 110000.,
       130000.,  38400.,  29616.,  48000.,  61398.,  43743.,  51805.,
        60000.,  51000.,  24000.,  65000.,  70000., 100000.,  55000.,
        59000.,  45904.,  57000.,  42000.,  55000.,  51600.,  20000.,
        33000.,  50000.,  60000.,  30000.,  29447.,  76000.,  33600.,
        24000.,  23900.,  43591.,  60000.,  14000.,  88000., 444000.,
        59000.,  20000.,  48000.,  23150.,  70000.,  72000.,  53170.,
        17000.,  20000.,  37000.,  48000.,  31000.,  15000.,  50500.,
       100000.,  32540.,  50000.,  70000.,  42000.,  47000.,  54000.,
       116000.,  40000.,  65000., 110000.,  38142.,  70000.,  82000.,
        45600.,  47000.,  18000.,  56000.,  60000.,  23800.,  24000.,
        28062.,  72000.,  42000.,  60000.,  22700.,  70000., 113996.,
       160000.,  60000.,  22000.,  35418.,  81733.,  50000.,  30000.,
        36000.,  38142.,  30000.,  50000.,  36000.,  36000.,  66000.,
        49000.,  80000.,  36000.,  14000.,  66000.,  55000.,  40000.,
       150000.,  56000.,  50000.,  34104.,  12000., 108000.,  42000.,
        30000.,  36000.,  62031.,  50400.,  24000., 100000.,  60000.,
        51630.,  45500.,  43000.,  36992.,  38142.,  24000.,  39000.,
        54000.,  54489.,  48000.,  68000.,  60000.,  60000.,  38142.,
        42000.,  50000.,  28000.,  40800.,  60000.,  19680.,  14400.,
        90000.,  61700.,  36000.,  40000.,  30000.,  75000.,  28000.,
        51000.,  77000.,  38000.,  96000.,  45000.,  60000.,  54000.,
        86000.,  55000.,  27930.,  30000.,  19616.,  34800.,  68000.,
        35000.,  27000.,  53400.,  63000.,  65000.,  42500.,  60000.,
        36000.,  47473.,  30000.,  48000.,  90000.,  48528.,  34000.,
        24000.,  33000.,  49000.,  50000.,  90000.,  37000.,  31000.,
        80000.,  50000.,  63000.,  80000.,  38000.,  70915.,  35000.,
        42000., 120000.,  50000.,  73500.,  60000.,  60000.,  23040.,
        14000.,  36003.,  43591.,  15000.,  54000.,  45000.,  55000.,
        48000., 120000.,  56000.,  50130.,  30000.,  55000.,  51000.,
        35000.,  48000.,  15000.,  27000.,  28000.,  84396.,  45000.,
        36000.,  33000.,  95000.,  44790.,  94704.,  71000.,  70000.,
        28000.,  18880.,  20000.,  35400.,  60000.,  33000.,  40867.,
       220000.,  44000.,  30000.,  32500.,  32000.,  26000.,  41204.,
        43640., 117701.,  57758.,  80000.,  49040.,  65000.,  72000.,
        70000.,  47598.,  35400., 120000.,  60000.,  60000.,  38000.,
        48000.,  25200.,  31000.,  63500.,  49200.,  39000.,  26666.,
        34800.,  60000.,  59640.,  29000.,  43000.,  49050.,  20000.,
        61027.,  50000.,  70000.,  61800.,  34039.,  47473., 120010.,
        32000.,  43380.,  22500.,  83500.,  52000.,  40340.,  75000.,
        72000.,  84000., 110000.,  45000.,  60005.,  30000.,  59500.,
        39600.,  37221.,  49040.,  25000.,  36000.,  70518.,  66000.,
        58000.,  32000.,  70000.,  54000.,  36000.,  48000.,  45000.,
        26000.,  54000.,  99500.,  66858., 103645.,  46000.,  55000.,
        77000.,  46000.,  56000.,  48300.,  62000.,  47000.,  27091.,
        60000.,  57400.,  21000.,  92735.,  58000.,  52000.,  69000.,
       102000.,  68000.,  49040., 108977.,  44400.,  75653.,  22800.,
        68000.,  59938.,  51000., 680000.,  35000.,  56967.,  24745.,
        57600.,  50000.,  25000.,  48000.,  75000.,  33000.,  40000.,
        36800.,  60000.,  60000.,  45000.,  24000.,  27000.,  35000.,
        35000.,  55000.,  25000.,  58000.,  46000.,  53000.,  31200.,
        55000.,  18000.,  17354.,  37000.,  32000., 152568.,  40000.,
        44000.,  98324.,  65000.,  38000.,  45000.,  54215.,  63605.,
        25790.,  26000.,  48000.,  41411.,  82000.,  57000.,  20000.,
        45000.,  52000.,  30000.,  53000.,  33000.,  49400.,  62000.,
        85000.,  22500.,  36000.,  35000.,  39000.,  32000.,  60000.,
        30000.,  62500.,  68656.,  30000.,  87280.,  36000.,  60000.,
        35000.,  51277.,  20000.,  57400.,  15000.,  76000.,  55000.,
        49095.,  38400.,  33500.,  21500.,  29860.,  63207.,  34000.,
        17180.,  38000.,  59000., 114800.,  60000.,  41760.,  47601.,
        31800.,  72000.,  48000.,  27000.,  35000., 150000.,  49200.,
        44479.,  12600.,  70000.,  25000.,  39000.,  55000.,  16000.,
        36830.,  36000.,  39000.,  60000.,  38400.,  32000.,  39000.,
        57000.,  70000.,  28334.,  31000.,  36000.,  40000.,  39276.,
        59938., 111841.,  32000.,  45000., 110000.,  63000.,  36000.,
        63207.,  38200.,  41800.,  21000.,  43640.,  49200.,  59000.,
        44400.,  50000.,  64000.,  31200.,  58000.,  40000.,  75000.,
        75000.,  70500.,  45000.,  11642.,  50480.,  61000.,  31000.,
        53000.,  60555.,  35000.,  49800., 108000.,  60000.,  80000.,
       102000.,  46315., 100000.,  64800.,  50000.,  47641.,  62000.,
        30000.,  31000.,  15000.,  26675.,  40000.,  50500.,  26000.,
        47902.,  27000.,  36000.,  38000., 134449.,  75000.,  44047.,
        45000.,  18000.,  50000.,  70000.,  15700.,  65000.,  31505.,
        94000.,  40000.,  55000.,  30000.,  65000.,  50000.,  32112.,
        60000.,  54000.,  54489.,  55000., 120000.,  30000.,  40000.,
        40990.,  41000.,  35000.,  26000.,  53355.,  80000.,  16000.,
        32000.,  95000.,  33000.,  65000., 101349.,  40000.,  35000.,
        36000.,  74000.,  43000.,  50000.,  70000.,  76289.,  18500.,
        48057.,  42000.,  19579.,  30000.,  32000.,  40000.,  95000.,
        30000.,  78000.,  55000.,  72000.,  41800.,  92000.,  27244.,
        37000.,  18584.,  44000.,  65000.,  27600., 120000.,  72000.,
        27000., 250000.,  30000.,  42000.,  68500.,  31000.,  40000.,
        33800.,  41000.,  19100.,  53000.,  39200.,  22000.,  38340.,
        16000.,  62000.,  35000.,  50000.,  30341.,  45000.,  44000.,
        25800.,  81000.,  70000.,  84000.,  32000.,  31000.,  40000.,
        56000.,  38000.,  87689.,  30000.,  15400.,  51000.,  16000.,
        42000.,  45500.,  27580.,  37700.,  40000., 175000., 261546.,
        42000.,  59000.,  48000.,  52000.,  56000.,  43400., 120000.,
        36000.,  46000.,  34873.,  82000.,  70000.,  71380.,  30000.,
        42000.,  20700.,  31680.,  46000.,  43000.,  30000.,  62000.,
       100000.,  47250.,  80000., 103000.,  38000.,  57000.,  27000.,
        54000.,  48000.,  29683.,  76800.,  48000.,  50000.,  32000.,
        42000.,  75000.,  90000.,  54647.,  25000.,  70000.])

In [47]:
import sys
np.set_printoptions(threshold = sys.maxsize)

In [52]:
print('\n Mean Salaries',np.mean(salaries))
print('\n Median Salaries',np.median(salaries))
print('\n', np.std(salaries))   # std --> standard deviations
print('\n', np.var(salaries))

 Mean Salaries 55894.53879686138

 Median Salaries 48000.0

 55170.37550939316

 3043770333.8474483